//export const WS_ORDER_HISTORY_CONNECTION_START: 'WS_ORDER_HISTORY_CONNECTION_START' = 'WS_ORDER_HISTORY_CONNECTION_START';
//export const WS_ORDER_HISTORY_CONNECTION_SUCCESS: 'WS_ORDER_HISTORY_CONNECTION_SUCCESS' = 'WS_ORDER_HISTORY_CONNECTION_SUCCESS';
//export const WS_ORDER_HISTORY_CONNECTION_ERROR: 'WS_ORDER_HISTORY_CONNECTION_ERROR' = 'WS_ORDER_HISTORY_CONNECTION_ERROR';
//export const WS_ORDER_HISTORY_CONNECTION_CLOSED: 'WS_ORDER_HISTORY_CONNECTION_CLOSED' = 'WS_ORDER_HISTORY_CONNECTION_CLOSED';
//export const WS_ORDER_HISTORY_GET_MESSAGE: 'WS_ORDER_HISTORY_GET_MESSAGE' = 'WS_ORDER_HISTORY_GET_MESSAGE';
//export const WS_ORDER_HISTORY_SEND_MESSAGE: 'WS_ORDER_HISTORY_SEND_MESSAGE' = 'WS_ORDER_HISTORY_SEND_MESSAGE';
import { createAction } from '@reduxjs/toolkit';

export const wsConnect = createAction<string, 'WS_ORDER_HISTORY_CONNECTION_START'>('WS_ORDER_HISTORY_CONNECTION_START');
export const wsOpen = createAction('WS_ORDER_HISTORY_CONNECTION_SUCCESS');
export const wsClose = createAction('WS_ORDER_HISTORY_CONNECTION_CLOSED');
export const wsMessage = createAction<any, 'WS_ORDER_HISTORY_GET_MESSAGE'>('WS_ORDER_HISTORY_GET_MESSAGE');
export const wsError = createAction<string, 'WS_ORDER_HISTORY_CONNECTION_ERROR'>('WS_ORDER_HISTORY_CONNECTION_ERROR');